/* Generated by TanStack Router's Vite plugin. Kept in the template so typechecks
   also work before the first dev/build command regenerates this file. */
import { Route as rootRoute } from "./routes/__root";
import { Route as indexRoute } from "./routes/index";

const routeTree = rootRoute.addChildren([indexRoute]);

export { routeTree };
