version: "2"
sql:
  - engine: "postgresql"
    schema: "../migrations"
    queries: "../../apps/api/internal"
    gen:
      go:
        package: "db"
        out: "../../apps/api/internal/platform/database/db"
